AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation Template for Create RDS:"
Resources:
  ShopperDB:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
      - !GetAtt DBEC2SecurityGroup.GroupId
      DBInstanceClass: db.t2.micro
      AllocatedStorage: "20"
      Engine: postgres
      EngineVersion: 12.5
      MasterUsername: postgres
      MasterUserPassword: postgres
      PubliclyAccessible: true
      DBName: eshopping
      Port: 5432
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '5432'
        ToPort: '5432'
        CidrIp: '0.0.0.0/0'   
Outputs:
  RdsEndpointAddress:
    Description: Endpoint
    Value: !GetAtt
      - ShopperDB
      - Endpoint.Address

